name: curved_nav_example
description: Example app demonstrating the curved_nav_fixed_center package.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  curved_nav_fixed_center:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 