name: curved_nav_fixed_center
description: A beautiful curved bottom navigation bar with fixed center curve and smooth animations. Currently under active development - contributions and feedback welcome!
version: 0.1.0+1
homepage: https://github.com/ctrlaziz/curved_nav_fixed_center
repository: https://github.com/ctrlaziz/curved_nav_fixed_center
issue_tracker: https://github.com/ctrlaziz/curved_nav_fixed_center/issues
maintainer: ctrlaziz

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true 